import React, {useEffect, useState} from 'react';
import {Alert, Box, Button, FormField, Header, Input, SpaceBetween, StatusIndicator, Table, Tabs, Textarea} from '@cloudscape-design/components';
export type Entry={id:string;record_id:string;version:string;kind:string;name:string;description:string;provider:string;data_handling:string;capabilities:string[];status:string;policy_reason:string;requestable:boolean;usable:boolean;origin:string;refreshed_at:number|null;fixture:boolean;approved:boolean;external:boolean;owner?:string;protocol?:string;parent_name?:string;descriptor_version?:string;source_revision?:string;inputSchema?:unknown;outputSchema?:unknown;supported?:boolean;execution_binding?:{status:string;last_checked:number|null}};
type Snapshot={items:Entry[];count:number;mode:string;agent_listing_implemented:boolean};
export default function AICatalog({api,onSelect}:{api:<T>(path:string,body?:unknown)=>Promise<T>;onSelect:(item:Entry)=>void}){
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[kind,setKind]=useState('model'),[query,setQuery]=useState(''),[error,setError]=useState(''),[selected,setSelected]=useState<Entry|null>(null),[purpose,setPurpose]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){setBusy(true);setError('');setSnapshot(null);setSelected(null);try{setSnapshot(await api<Snapshot>('/catalog'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void refresh();},[]);
 const items=(snapshot?.items||[]).filter(x=>(x.kind===kind)&&(x.name+' '+x.description+' '+x.provider).toLowerCase().includes(query.toLowerCase()));
 const table=<Table loading={busy} header={<Header counter={`(${items.length})`}>Discoverable capabilities</Header>} items={items} columnDefinitions={[
  {id:'name',header:'Capability',cell:x=><SpaceBetween size="xxs"><Box fontWeight="bold">{x.name}</Box><Box>{x.description}</Box><Box variant="small">{x.record_id} · {x.version}</Box>{x.parent_name&&<Box>Parent server: {x.parent_name}</Box>}{x.supported===false&&<StatusIndicator type="stopped">Unsupported descriptor · nonselectable</StatusIndicator>}</SpaceBetween>},
  {id:'provider',header:'Provider / origin',cell:x=><SpaceBetween size="xxs"><Box>{x.provider}</Box><Box>{x.origin}</Box><Box>{x.protocol} · Owner: {x.owner||'Not declared'}</Box>{x.descriptor_version&&<Box>Descriptor: {x.descriptor_version}</Box>}{x.source_revision&&<Box variant="small">Revision: {x.source_revision.slice(0,12)}</Box>}{x.inputSchema!==undefined&&<details><summary>Declared operation schemas (safe projection)</summary><pre>{JSON.stringify({inputSchema:x.inputSchema,outputSchema:x.outputSchema},null,2)}</pre></details>}<Box variant="small">{x.fixture?'Development fixture · not live':x.refreshed_at?'Metadata refreshed '+new Date(x.refreshed_at*1000).toLocaleString():'Refresh evidence unavailable'}</Box></SpaceBetween>},
  {id:'policy',header:'Data handling',cell:x=><SpaceBetween size="xxs"><Box>{x.data_handling}</Box><Box>{x.capabilities.join(', ')}</Box></SpaceBetween>},
  {id:'access',header:'Access',cell:x=><SpaceBetween size="xs"><StatusIndicator type={x.usable?'success':x.requestable?'pending':'stopped'}>{x.status}</StatusIndicator><Box>{x.policy_reason}</Box>{x.execution_binding&&<Box>Execution binding: {x.execution_binding.status} · {x.execution_binding.last_checked?'Checked '+new Date(x.execution_binding.last_checked*1000).toLocaleString():'Not checked'}</Box>}{x.requestable&&<Button onClick={()=>{setSelected(x);setPurpose('');setNotice('');}}>Request access</Button>}{['model','tool','skill'].includes(x.kind)&&x.supported!==false&&(!x.fixture||x.usable)&&<Button onClick={()=>onSelect(x)}>{x.fixture?'Use in builder':'Add to draft (not deployment)'}</Button>}</SpaceBetween>}
 ]} empty={<Box>No discoverable capabilities match. Hidden resources are not included in counts or search. Requesting a missing capability is a separate future workflow, not creation of an existing catalog item.</Box>}/>;
 return <SpaceBetween size="l"><Alert type="info">AI Catalog aggregates approved business capabilities, not a tool store. Foundation Library owns blueprint configuration and code separately. Models come from Model Gateway. Registry describes servers, agents, skills and other resources; Tools are declared callable operations, internal or external, not URLs. Discovery approval is not execution readiness. Gemini is external and not configured.</Alert>{snapshot?.mode==='fixture'&&<Alert type="warning">Development fixture catalog only. No live service discovery has been performed.</Alert>}{snapshot?.mode==='live'&&<Alert type="warning">Live metadata only. Runtime, gateway execution and evaluation acceptance remain disabled.</Alert>}{error&&<Alert type="error" header={error.includes('NotConnected')?'Not connected':'Catalog unavailable'}><span>{error}</span> No synthetic catalog is substituted.</Alert>}{notice&&<Alert type="success">{notice}</Alert>}<Button iconName="refresh" disabled={busy} onClick={()=>void refresh()}>Refresh catalog</Button><Input ariaLabel="Search AI catalog" placeholder="Search discoverable metadata" value={query} onChange={({detail})=>setQuery(detail.value)}/><Tabs activeTabId={kind} onChange={({detail})=>{setKind(detail.activeTabId);setSelected(null);}} tabs={[{id:'model',label:'Models'},{id:'mcp_server',label:'MCP servers'},{id:'tool',label:'Tools'},{id:'skill',label:'Skills'},{id:'agent',label:'Agents'},{id:'resource',label:'Other resources'}].map(t=>({...t,content:table}))}/>{selected&&<SpaceBetween size="m"><Header variant="h2">Request access: {selected.name}</Header><FormField label="Workspace business purpose" description="The server scopes this request to your signed-in user and workspace. A distinct administrator must approve with a reason."><Textarea ariaLabel="Catalog request purpose" value={purpose} onChange={({detail})=>setPurpose(detail.value)}/></FormField><Button variant="primary" disabled={busy||purpose.trim().length<5} onClick={async()=>{setBusy(true);setError('');try{await api('/requests',{component_id:selected.id,reason:purpose});setSelected(null);setNotice('Access request recorded. Approval grants access only; it does not onboard a connector.');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Submit access request</Button></SpaceBetween>}</SpaceBetween>;
}
